# These are supported funding model platforms
custom: ['https://www.blockchain.com/btc/address/1Ep9VoyNtnNiGoXM52V6NwcMh4SZ9bxkAG', 'https://etherscan.io/address/0xfac5e46ffe12ec1fc2830d95c22e6583d163d7f9']
