name: Erlang CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:21.2

    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 eunit
    - name: Run Geas
      run: rebar3 geas
